name: CI/CD for Minimal API

on:
  push:
    branches:
      - main  # Auto-deploys to Staging
  workflow_dispatch:  # Manual trigger for Production

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run unit tests
        run: dotnet test --no-restore --verbosity normal

      - name: Publish API
        run: dotnet publish -c Release -o ./publish

  deploy-staging:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://minapi-staging-gbfbcze3bwhfg5ee.westeurope-01.azurewebsites.net/
    steps:
      - name: Deploy to Staging (minapi-staging)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'minapi-staging'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          package: ./publish

  deploy-production:
    needs: build-and-test
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://minapi-production-h0grf5fsdnasffbf.westeurope-01.azurewebsites.net
    steps:
      - name: Deploy to Production (minapi-production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'minapi-production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PRODUCTION }}
          package: ./publish
